name: Deploy Frontend to EC2

on:
  push:
    branches:
      - test  # 🔹 Se ejecutará cuando haya un push en la rama test test1 test2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 🚀 Clonar Repositorio
      uses: actions/checkout@v3

    - name: 🔑 Configurar Acceso SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY_FRONT }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST_FRONT }} >> ~/.ssh/known_hosts

        - name: 📡 Conectar y Desplegar el Frontend en EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST_FRONT }} << 'EOF'
            echo "✅ Conexión a EC2 exitosa. Iniciando despliegue..."
            
            # Ir a la carpeta del frontend
            cd /home/ubuntu/frontend-app/front-distribuida/login-app
      
            # Obtener cambios del repositorio
            git fetch origin test
            CHANGES=$(git rev-list HEAD...origin/test --count)
      
            if [ "$CHANGES" -gt 0 ]; then
              echo "🔄 Se detectaron cambios. Actualizando código..."
              git reset --hard
              git clean -fd
              git pull origin test --force
      
              # Reiniciar la aplicación solo si hubo cambios
              pm2 restart frontend || pm2 start npm --name frontend -- start -- --host 0.0.0.0
              echo "✅ Aplicación reiniciada con los nuevos cambios."
            else
              echo "⚡ No hay cambios en el código. No se reinicia la aplicación."
            fi
          EOF
      